//Copyright timeanddate.com 2025, do not use without permission
(function(){function v(a){a.purpose.consents[1]?(d.set("gdpr","acc"),d.set("p1",0)):(d.set("gdpr","rej"),d.set("p1",1),d.setTargeting("pfo","1"))}function k(){m=!1;k=function(){};window.consentDataReady=k;d.__logEvent("S2");n.hasEnabled()&&!d.get("p1")?(n.forEach("requestBids"),setTimeout(function(){d.send()},f.timeout+2E3)):d.send()}function F(a){function c(b){0<a?setTimeout(function(){m&&F(a-1)},1E3):d.send()}m&&("function"!=typeof window.__tcfapi?c("Step 3.6: CMP not yet found"):__tcfapi("ping",
2,function(a){if(m){var b=a&&a.cmpStatus,g=a&&"visible"!=a.displayStatus;"loaded"!=b&&"disabled"!=b&&"error"!=b||!g?c("Step 3.7b: CMP ping not ready yet (display="+(a&&a.displayStatus||"na")+", status="+(b||"na")+")"):d.push(function(){d.send()})}}))}var f=window.AdMgrCfg;if(f){var p=window.AdMgr;p=p&&p._q||[];var w=f.techs,r=f.slots||[],M=f.gdprStart||"na",N=f.logUrl,O=f.rotEmpty,G=f.pf,H=f.ppid||null,I=f.lateLoad||"",d=function(){function a(e){if(!e)return"";e=e.split("/");return e[e.length-1]||
""}function c(e,a,b){e=[(new Date).getTime()-B,e];a&&e.push(a);void 0!==b&&null!==b&&e.push(b);v.push(e)}function b(){return 0<(document.referrer||"").indexOf("timeanddate")}function u(){p||(window.jcb&&window.TADhba?(p=1,jcb(N+"&"+TADhba(),function(){})):setTimeout(u,1E3))}function g(a){googletag.cmd.push(a)}function x(a,b){b&&g(function(){googletag.pubads().setTargeting(a,b)})}function h(){if(!r){r=!0;for(var e=[],A=0;A<l.length;A++)l[A].n&&e.push(a(l[A].n));c("S4",e.join(","));x("pbv",window.pbv);
x("si",b()?"2":"1");x("gdpr",C.gdpr);G&&(d.get("p1")||x("pf",G));l.forEach(function(a){if(a.t)for(var e=0;e<a.t.length;e++){var b=a.t[e];"pf"==b[0]&&d.get("p1")||a.S&&a.S.setTargeting(b[0],b[1])}});g(function(){googletag.enableServices();c("42");googletag.pubads().refresh(AD.s);if(f.lateLoadOps)for(var a=0;a<f.lateLoadOps.length;a++){var e=f.lateLoadOps[a],b=AD[e.varName];b&&function(a,e){var b=function(){"refresh"===e.type?googletag.pubads().refresh([a]):"displayRefresh"===e.type&&(googletag.display(a),
window.setTimeout(function(){googletag.pubads().refresh([a])},e.delay||0))};e.delay&&"refresh"===e.type?window.setTimeout(b,e.delay):b()}(b,e)}I&&(new Function(I))()})}}function k(){if(!D){D=!0;var e=m[0];c("53",a(e.n),e.rot);g(function(){googletag.pubads().refresh([e.S])})}}function q(e){if(e.slot){var b=J(e);if(b){b.hasAd=0;b.loadedAt=Date.now();if(e.isEmpty){if(c("6N",a(b.n)),b.na){if(e=document.getElementById(b.i))e=e.parentElement;e&&("invisible"===b.na?e.style.visibility="hidden":"remove"===
b.na&&(e.style.display="none"))}}else b.hasAd=1,e=e.advertiserId?e.advertiserId:null,b.winner=e,c("6Y",a(b.n),e);if(y&&m.length&&m[0]===b)a:for(y=!1;0<t.length;)if(b=t.shift(),K(b),y)break a}}setTimeout(u,1E3)}function K(a){if(a.r<a.ro&&(a.hasAd||O)){y=!0;a.e=!a.hasAd;a.hasAd=0;D=!1;E=JSON.parse(JSON.stringify(w));a.r++;m=[a];if("invisible"===a.na){var b=document.getElementById(a.i);b&&(b=b.parentElement);b&&(b.style.visibility="")}b=""+a.r;a.e&&(b+="e");a.S.setTargeting("rot",b);a.rot=b;d.get("p1")?
k():(setTimeout(k,(d.timeout||3E3)+2E3),n.forEach("requestBidsRefresh",a))}}function J(a){var b=null;if(a.slot)a:{a=a.slot.getAdUnitPath();for(b=0;b<l.length;b++){var e=l[b];if(e.n===a){b=e;break a}}b=null}return b}var p=0,r=0,l=[],m=[],t=[],y=!1,v=[],B=(new Date).getTime(),z=JSON.parse(JSON.stringify(w)),E=JSON.parse(JSON.stringify(w)),D=0,C={gdpr:M};addEventListener("impressionViewableRotate",function(a){a=a.detail.o;a.ro&&(y?t.push(a):K(a))},!0);g(function(){f.hasCMP&&setTimeout(function(){F(0)},
5E3);googletag.pubads().disableInitialLoad();googletag.pubads().addEventListener("slotRenderEnded",q);H&&googletag.pubads().setPublisherProvidedId(H)});return{addSlot:function(a){a.wm&&a.wm>window.innerWidth&&(a.wf.i=a.i,a=a.wf);a.r=0;a.rot="0";a.a9=function(){return{slotID:a.i,slotName:a.n,sizes:a.s}};l.push(a);if(a.css){var b=document.createElement("style");b.textContent=a.css;document.head.appendChild(b)}},slot:function(a){return l[a]},a9slot:function(a){return l[a].a9()},gptSlot:function(a){var b=
l[a];b&&g(function(){b.S=googletag.defineSlot(b.n,b.s,b.i);b.S.addService(googletag.pubads());b.c&&googletag.setConfig(b.c);AD.s.push(b.S)})},slotByGPTEvent:J,dispSlot:function(a){var b=l[a];g(function(){googletag.display(b.i)})},bidsIn:function(a){delete z[a];0==Object.keys(z).length&&h()},bidsInR:function(a){delete E[a];0==Object.keys(E).length&&k()},push:g,setTargeting:x,send:h,set:function(a,b){C[a]=b},get:function(a){return C[a]},rendered:q,isSecond:b,done:function(){return p},getLog:function(){return v},
__logEvent:c}}();window.AdMgr=d;for(var h=0;h<r.length;h++)d.addSlot(r[h]);for(h=0;h<r.length;h++)d.gptSlot(h);for(h=0;h<p.length;h++){var B=p[h],z=B[0];if(d[z])d[z](B[1])}d.__logEvent("S1");var n=function(){var a={},c={};return{register:function(b,c){a[b]=c;a[b]._name=b;a[b]._enabled=!1;a[b]._config={}},enable:function(b,d){a[b]&&(c[b]=!0,a[b]._enabled=!0,a[b]._config=d||{})},forEach:function(b){var d=Array.prototype.slice.call(arguments,1),g;for(g in c)c[g]&&a[g]&&a[g][b]&&a[g][b].apply(a[g],d)},
hasEnabled:function(){for(var a in c)if(c[a])return!0;return!1},get:function(b){return a[b]}}}();n.register("aps",{init:function(){!function(a,c,b){c[a]||(c[a]={init:function(){c[a]._Q.push(["i",arguments])},fetchBids:function(){c[a]._Q.push(["f",arguments])},setDisplayBids:function(){},targetingKeys:function(){return[]},_Q:[]})}("apstag",window,document)},setupConfig:function(){window.TADaps={b:[]};var a=this._config;a&&a.pubID&&apstag.init({pubID:a.pubID,adServer:"googletag"})},requestBids:function(){for(var a=
[],c=0;c<r.length;c++){var b=d.a9slot(c);b&&a.push(b)}window.TADaps.t=+new Date;apstag.fetchBids({slots:a,timeout:f.timeout+300,params:{adRefresh:"0"}},function(a){d.push(function(){window.TADaps.e=+new Date;apstag.setDisplayBids();AD.s.forEach(function(a){var b=0;(a=a.getTargeting("amznbid"))&&0<a.length&&(b=a[0]);window.TADaps.b.push(b)});d.__logEvent("A2");d.bidsIn("aps")})})},requestBidsRefresh:function(a){window.TADaps.t=+new Date;apstag.fetchBids({slots:[a.a9()],timeout:f.timeout,params:{adRefresh:"1"}},
function(c){d.push(function(){window.TADaps.b=[];window.TADaps.e=+new Date;if(a.S)for(var b=apstag.targetingKeys&&apstag.targetingKeys().length?apstag.targetingKeys():["amznbid","amznp","amzniid"],c=0;c<b.length;c++)a.S.clearTargeting(b[c]);apstag.setDisplayBids();AD.s.forEach(function(a){var b=0;(a=a.getTargeting("amznbid"))&&0<a.length&&(b=a[0]);window.TADaps.b.push(b)});d.bidsInR("aps")})})},htmlAfter:function(){},debugFunctions:function(){}});n.register("pb",{init:function(){window.pbjs=window.pbjs||
{};pbjs.que=pbjs.que||[];pbjs.bidderSettings={standard:{storageAllowed:!0}}},setupConfig:function(){var a=this._config,c=f.hasCMP||!1;a&&pbjs.que.push(function(){if(a.pbjsConfig){var b=a.pbjsConfig;b.priceGranularity={buckets:[{min:0,max:4,increment:.01},{min:4,max:8,increment:.02},{min:8,max:20,increment:.05},{min:20,max:30,increment:.1},{min:30,max:50,increment:.25},{min:50,max:100,increment:1}]};b.enableTIDs=!0;b.consistentTIDs=!0;b.enableSendAllBids=!0;b.ortb2=b.ortb2||{};b.ortb2.device=b.ortb2.device||
{};b.ortb2.device.dnt="1"===navigator.doNotTrack?1:0;b.bidderSequence="fixed";b.bidderTimeout=f.timeout;pbjs.setConfig(b)}if(a.aliases){for(var d in a.aliases)a.aliases.hasOwnProperty(d)&&pbjs.aliasBidder(a.aliases[d],d);pbjs.setConfig({aliases:a.aliases})}if(a.extraConfigs)for(var g in a.extraConfigs)a.extraConfigs.hasOwnProperty(g)&&pbjs.setConfig(a.extraConfigs[g],!0);if(a.analytics&&a.analytics.length)for(b=0;b<a.analytics.length;b++)pbjs.enableAnalytics(a.analytics[b]);!c&&window.consentDataReady&&
k()})},requestBids:function(){var a=this,c=this._config;c&&c.adUnits&&Array.isArray(c.adUnits)&&0!==c.adUnits.length&&pbjs.que.push(function(){d.get("p1")&&pbjs.setConfig({deviceAccess:!1});for(var b={},f=0;f<r.length;f++){var g=d.slot(f);g&&(b[g.n]=!0)}f=c.adUnits.filter(function(a){return b[a.code]});pbjs.addAdUnits(f);pbjs.requestBids({bidsBackHandler:function(){var b=0,c=0,f=pbjs.getBidResponses(),g;for(g in f)if(f.hasOwnProperty(g))for(var u=f[g].bids,h=0;h<u.length;h++)u[h].cpm&&(b++,c=Math.max(c,
u[h].cpm));d.push(function(){try{pbjs.setTargetingForGPTAsync(),d.__logEvent("P2"),a._config.outOfPageTargeting&&(new Function(a._config.outOfPageTargeting))()}catch(P){}d.bidsIn("pb")});d.setTargeting("tadbid",""+b);d.highBid=c}})})},requestBidsRefresh:function(a){window.pbjs&&pbjs.requestBids({timeout:2*f.timeout,adUnitCodes:[a.n],bidsBackHandler:function(){d.push(function(){try{if(a.S&&pbjs.getAdserverTargetingKeys)for(var c=pbjs.getAdserverTargetingKeys(),b=0;b<c.length;b++)a.S.clearTargeting(c[b]);
pbjs.setTargetingForGPTAsync([a.n])}catch(u){}d.bidsInR("pb")})}})},htmlAfter:function(){if(this._config.headHtml){var a=document.createElement("div");a.innerHTML=this._config.headHtml;a=a.getElementsByTagName("script");for(var c=0;c<a.length;c++){var b=a[c],d=document.createElement("script");b.src?(d.src=b.src,d.async=!0):d.textContent=b.textContent;document.head.appendChild(d)}}},debugFunctions:function(){window.tad_debug_pbjs_bids=function(){var a=pbjs.getBidResponses(),c;for(c in a){var b=a[c].bids;
if(b)for(var d=0;d<b.length;d++){var f=b[d];f.cpm?console.log("BID:",c,f.bidder,f.size,"$"+f.cpm):console.log("No bid:",c,f.bidder,"No bid or error")}else console.log(c,"No bids")}a=pbjs.getAdserverTargeting();for(c in a)b=a[c],b.hb_pb?console.log("BID SENT IN",c,b.hb_bidder,b.hb_size,b.hb_pb):console.log("BID SENT IN",c,b)}}});for(var q in w)w[q]&&n.enable(q,f.bidderConfigs&&f.bidderConfigs[q]||{});n.forEach("init");q=window.AdMgrSetup||{};n.forEach("setupConfig");var L=!1,t=null,m=!!f.hasCMP;window.cmpEvent=
function(a,c){c&&(c=a.eventStatus,"cmpuishown"==c?(L=!0,d.__logEvent("CU")):"tcloaded"==c?L||(v(a),d.__logEvent("CL"),k()):"useractioncomplete"==c&&(v(a),t&&clearTimeout(t),t=setTimeout(function(){t=null;d.__logEvent("CC");k()},50)))};window.consentDataReady=k;f.hasCMP||k();d.push(function(){if(f.targeting)for(var a in f.targeting)f.targeting.hasOwnProperty(a)&&googletag.pubads().setTargeting(a,""+f.targeting[a]);if(f.outOfPageSlots)for(a=0;a<f.outOfPageSlots.length;a++){var c=f.outOfPageSlots[a],
b=!0;"isSecond"===c.condition&&(b=0<(document.referrer||"").indexOf("timeanddate"));if(b)try{var h=googletag.defineOutOfPageSlot(c.slot,googletag.enums.OutOfPageFormat[c.format]);h&&(AD[c.varName]=h,h.addService(googletag.pubads()))}catch(g){}}googletag.pubads().enableSingleRequest();d.__logEvent&&d.__logEvent("S6")});n.forEach("htmlAfter");q.after&&q.after()}})();
